# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'ARFurniture' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for ARFurniture

    	pod 'MBProgressHUD'
   	pod 'SDWebImage'
   	pod 'Reachability'
    	pod 'PageMenu'
	
  target 'ARFurnitureUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
